// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.11.2
// source: addressbook.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AddressbookClient is the client API for Addressbook service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddressbookClient interface {
	GetAddress(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*AddressResponse, error)
}

type addressbookClient struct {
	cc grpc.ClientConnInterface
}

func NewAddressbookClient(cc grpc.ClientConnInterface) AddressbookClient {
	return &addressbookClient{cc}
}

func (c *addressbookClient) GetAddress(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*AddressResponse, error) {
	out := new(AddressResponse)
	err := c.cc.Invoke(ctx, "/proto.Addressbook/GetAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressbookServer is the server API for Addressbook service.
// All implementations must embed UnimplementedAddressbookServer
// for forward compatibility
type AddressbookServer interface {
	GetAddress(context.Context, *AddressRequest) (*AddressResponse, error)
	mustEmbedUnimplementedAddressbookServer()
}

// UnimplementedAddressbookServer must be embedded to have forward compatible implementations.
type UnimplementedAddressbookServer struct {
}

func (UnimplementedAddressbookServer) GetAddress(context.Context, *AddressRequest) (*AddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddress not implemented")
}
func (UnimplementedAddressbookServer) mustEmbedUnimplementedAddressbookServer() {}

// UnsafeAddressbookServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddressbookServer will
// result in compilation errors.
type UnsafeAddressbookServer interface {
	mustEmbedUnimplementedAddressbookServer()
}

func RegisterAddressbookServer(s grpc.ServiceRegistrar, srv AddressbookServer) {
	s.RegisterService(&Addressbook_ServiceDesc, srv)
}

func _Addressbook_GetAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressbookServer).GetAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Addressbook/GetAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressbookServer).GetAddress(ctx, req.(*AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Addressbook_ServiceDesc is the grpc.ServiceDesc for Addressbook service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Addressbook_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Addressbook",
	HandlerType: (*AddressbookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAddress",
			Handler:    _Addressbook_GetAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "addressbook.proto",
}
